thread:
    path:     /
    defaults: { _controller: "APiszczekDemoBundle:Thread:index" }

thread_show:
    path:     /{id}/show
    defaults: { _controller: "APiszczekDemoBundle:Thread:show" }

thread_new:
    path:     /new
    defaults: { _controller: "APiszczekDemoBundle:Thread:new" }

thread_create:
    path:     /create
    defaults: { _controller: "APiszczekDemoBundle:Thread:create" }
    requirements: { _method: post }

thread_edit:
    path:     /{id}/edit
    defaults: { _controller: "APiszczekDemoBundle:Thread:edit" }

thread_update:
    path:     /{id}/update
    defaults: { _controller: "APiszczekDemoBundle:Thread:update" }
    requirements: { _method: post|put }

thread_delete:
    path:     /{id}/delete
    defaults: { _controller: "APiszczekDemoBundle:Thread:delete" }
    requirements: { _method: post|delete }
