a_piszczek_demo_index:
    pattern:  /
    defaults: { _controller: APiszczekDemoBundle:Overview:index }  

a_piszczek_demo_about:
    pattern:  /about
    defaults: { _controller: APiszczekDemoBundle:Overview:about }  

a_piszczek_demo_upload:
    pattern:  /upload
    defaults: { _controller: APiszczekDemoBundle:Overview:upload }  

a_piszczek_demo_feedRemove:
    pattern:  /feed/remove
    defaults: { _controller: APiszczekDemoBundle:Overview:feedRemove }  

